# 基本博客设置
baseurl: "" # 网站的子路径，例如 /blog/
# 在 GitHub 上托管时设置为 ''
url: "" # 网站的基本主机名和协议
# `http://<username>.github.io` - 适用于 GitHub

blog:
  title: "ShengCaiTeam"
  description: >
    "关于[代码](/code).[生活](/life).[宇宙](/read)和[一切](/)。"
  # 布局配置
  logo_path: "assets/img/dactl.svg" # logo 文件的路径
  search_path:
    "ShengCaiTeam.github.io"
    # 在归档页面中搜索框需要的路径
  hero_layout: true # 启用博客和文章的英雄布局
  hero_placeholder: "assets/img/generic_hero.jpg" # 英雄图像的占位符
  excerpts: true # 在博客页面上显示摘录而不是完整的文章内容
  inline_footnotes: true # 启用/禁用内联脚注
  titles_only: false # 在主博客页面上仅显示文章标题

  # 字体
  font: '"Rubik", -apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif'
  load_google_fonts: "Rubik:400,400italic,700,700italic"

# 作者信息
author:
  fullname: China Panda
  rss: true # 生成 RSS 源并在标题中显示其图标
  mail: your@email.com # 更改为你的电子邮件地址
  twitter: twitter 用户名
  github: github 用户名
  youtube: youtube 用户名
  stackoverflow: stackoverflow 用户名
  disqus: shengcaiteam # 你的 disqus 站点名称
  google_analytics: # 'UA-XXXXXXXX-X'
  photo: "uploads/me2.png"
  photo2x: "uploads/me.png"

## !!
## 高级博客设置
## 除非你知道自己在做什么，否则不应更改此处的任何内容

# 插件
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# 永久链接
#设置了 permalink: posts/:slug 后，这篇文章的 URL 将会是： http://your-domain.com/posts/hello-world
permalink: posts/:slug
#设置了 permalink: /:year/:month/:day/:slug/ 后，这篇文章的 URL 将会是： http://your-domain.com/2024/08/01/hello-world/
# permalink: /:year/:month/:day/:slug/
# 文章
excerpt_separator: "<!--break-->"

# 分页
paginate: 5
paginate_path: "/page-:num/"

# 标签
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  - scope:
      path: ""
      type: my_tags
    values:
      layout: blog-by-tag

# 读取处理
exclude:
  - "README.md"
  - "README.html"

# https://github.com/jekyll/jekyll/issues/4619
# Markdown 和高亮设置
markdown: kramdown
# !github-pages! 强制 › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# 自 Jekyll 3 起，默认高亮器是 Rouge（在 v44 中取代了 Pygments.rb）
highlighter: rouge

# 更多 › http://kramdown.gettalong.org/quickref.html
# 选项 › http://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge 高亮器在 Kramdown 中 › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span 和 block 元素选项会回退到全局选项
  syntax_highlighter_opts:
    # Rouge 选项 › https://github.com/jneen/rouge#full-options
    # css_class: 'highlight'
    # line_numbers: true # 糟糕的主意，span 不需要行号且会继承此选项
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Sass 设置
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# HTML 压缩
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  endings: all
  comments: ["<!-- ", " -->"]
  blanklines: true
  profile: false
  ignore:
  envs: [local]
